### PR TITLE
Fix reduce memory usage

### LINKED ISSUE #143: Process aborts with 'out of memory' when using 2.0.0
- Operating System: OSX 10.14.6
- Node Version: 10.16.0
- NPM Version: 6.9.0
- webpack Version: 4.39.3
- terser-webpack-plugin Version: 2.0.0

### Expected Behavior

Process does not abort

### Actual Behavior

```
$ NODE_ENV=production ./node_modules/.bin/webpack --loglevel notice

<--- Last few GCs --->

[84294:0x102843000]    55749 ms: Mark-sweep 1312.4 (1444.3) -> 1305.0 (1446.3) MB, 622.0 / 0.0 ms  (average mu = 0.099, current mu = 0.040) allocation failure scavenge might not succeed
[84294:0x102843000]    56388 ms: Mark-sweep 1315.7 (1446.3) -> 1308.6 (1448.8) MB, 613.1 / 0.0 ms  (average mu = 0.070, current mu = 0.040) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3aa9ebf5be3d]
Security context: 0x37c8eea1e6e9 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [0x37c895d8d969] [/Users/nick/Projects/origin/node_modules/terser-webpack-plugin/node_modules/webpack-sources/lib/applySourceMap.js:~58] [pc=0x3aa9ed4fe2c4](this=0x37c83a5026f1 <undefined>,chunk=0x37c803a7d979 <String[14]: createElement(>,middleMapping=0x37c8171046d9 <Object map = 0x37c835e45c79>)
    2: SourceNode...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003cf99 node::Abort() [/usr/local/bin/node]
 2: 0x10003d1a3 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001b7835 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x100585682 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x100588155 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 6: 0x100583fff v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x1005821d4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10058ea6c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x10058eaef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x10055e434 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
11: 0x1007e6714 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x3aa9ebf5be3d 
13: 0x3aa9ed4fe2c4 
14: 0x3aa9ed4b7d28 
Abort trap: 6
```

### Code

https://github.com/OriginProtocol/origin/blob/master/dapps/marketplace/webpack.config.js

### How Do We Reproduce?

```
git clone https://github.com/OriginProtocol/origin.git
cd origin
# Update dapps/marketplace/package.json to use v2.0.0 of terser plugin
yarn
cd dapps/marketplace
yarn build
```

### PR DESCRIPTION
**Pull request by evilebottnawi**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

reduce memory usage

fixes #143

### Breaking Changes

No

### Additional Info

- lazy task generation
- fix concurrency for workers

### CODE REVIEW

File: src/TaskRunner.js [hunk 1]
```diff
@@ -44,34 +58,53 @@ export default class TaskRunner {
...
             );
           }
 
-          return result;
-        };
-
-        if (this.cache.isEnabled()) {
-          return this.cache.get(task).then((data) => data, enqueue);
-        }
+          return enqueue(task);
```
Comment (cjlarose) [inline src/TaskRunner.js]: I don't think `plimit` makes any guarantee about the order of execution of the enqueued functions. I think this means that `enqueue(task)` can be called in any order and therefore `task.callback(taskResult)` can be, too.

This seems like it has the potential to introduce non-determinism whenever parallelism is enabled. That is, if I run my webpack build twice, I expect it to produce the same outputs. This change seems to break that guarantee whenever `extractComments` is on since comment extraction depends on processing the results in a particular order.

It is important that this plugin is deterministic because nondeterministic builds needlessly invalidate long-term caches.

Comment (evilebottnawi) [reply src/TaskRunner.js]: Yes, we need sort properties of `allExtractedComments` here https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L509

Comment (evilebottnawi) [reply src/TaskRunner.js]: I will fix it in near future

Comment (evilebottnawi) [reply src/TaskRunner.js]: Hm, not sure problem exists:
- https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L511

We sort comments inside each file, so output is deterministic

- https://github.com/webpack/webpack/blob/bd8c74c0bba3a7732e51a763bc291bd76267e7f7/lib/stats/DefaultStatsPresetPlugin.js#L166

Webpack sort assets by default

Comment (cjlarose) [reply src/TaskRunner.js]: Ok, I think you're right. Since comments are sorted and then de-duped after being collected in `allExtractedComments`, I think the output is deterministic.
