### PR TITLE
Fix types incompatibility of PredefinedOptions.ecma and MinifyOptions.ecma

### LINKED ISSUE #470: Types of PredefinedOptions.ecma and MinifyOptions.ecma are incompatible
### Bug report
This commit https://github.com/webpack-contrib/terser-webpack-plugin/commit/d7ea08fada95a542c219a7c3beb0fea5abf6aab0#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccceR55 introduced a change of `PredefinedOptions.ecma`  type.
From `ecma?: string | number | undefined;` to `ecma?: any;` while, in terser (https://github.com/terser/terser/blob/v5.10.0/tools/terser.d.ts#L176), the type of `MinifyOptions.ecma` is `ecma?: ECMA;`.
As these two properties have different types, it creates an error when running webpack.

### Actual Behavior
When trying to run `webpack --config ./build/webpack.config.js --mode=development`, it fails and outputs the error below 
```
yarn run v1.22.17
$ webpack --config ./build/webpack.config.js --mode=development
[webpack-cli] Failed to load '<path>/build/webpack.config.js' config
[webpack-cli] build/webpack.config.ts:44:13 - error TS2322: Type '{ ecma: number; module: true; sourceMap: true; mangle: { properties: true; toplevel: true; }; keep_classnames: true; compress: true; output: { comments: false; beautify: false; }; }' is not assignable to type 'MinimizerOptions<MinifyOptions>'.
  Type '{ ecma: number; module: true; sourceMap: true; mangle: { properties: true; toplevel: true; }; keep_classnames: true; compress: true; output: { comments: false; beautify: false; }; }' is not assignable to type 'MinifyOptions'.
    Types of property 'ecma' are incompatible.
      Type 'number' is not assignable to type 'ECMA'.

44             terserOptions: {
               ~~~~~~~~~~~~~

  node_modules/terser-webpack-plugin/types/index.d.ts:230:7
    230       terserOptions?: MinimizerOptions<T> | undefined;
              ~~~~~~~~~~~~~
    The expected type comes from property 'terserOptions' which is declared here on type 'BasePluginOptions & { minify?: MinimizerImplementation<MinifyOptions>; terserOptions?: MinimizerOptions<MinifyOptions>; }'

error Command failed with exit code 2.
```

### Expected Behavior
`PredefinedOptions.ecma` (https://github.com/webpack-contrib/terser-webpack-plugin/blob/v5.3.0/types/index.d.ts#L293) and `MinifyOptions.ecma` (https://github.com/terser/terser/blob/v5.10.0/tools/terser.d.ts#L176) should have the same type.

### How Do We Reproduce?
Use terser v5.10.0 and terser-webpack-plugin v5.3.0 with the following webpack configuration:
```js
optimization: {
    minimizer: [
        new TerserPlugin({
            terserOptions: {
                ecma: 2019,
            }
        })
    ]
}
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
  System:
    OS: Linux 5.15 Pop!_OS 21.10
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 640.71 MB / 15.36 GB
  Binaries:
    Node: 16.13.1 - /tmp/yarn--1643646016187-0.620448205129027/node
    Yarn: 1.22.17 - /tmp/yarn--1643646016187-0.620448205129027/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Firefox: 96.0
  Packages:
    css-loader: ^6.4.0 => 6.5.1 
    dotenv-webpack: ^7.0.3 => 7.1.0 
    progress-bar-webpack-plugin: ^2.1.0 => 2.1.0 
    sass-loader: ^12.1.0 => 12.4.0 
    style-loader: ^3.3.0 => 3.3.1 
    terser-webpack-plugin: ^5.2.5 => 5.3.0 
    ts-loader: ^9.2.6 => 9.2.6 
    webpack: ^5.56.1 => 5.67.0 
    webpack-cli: ^4.8.0 => 4.9.2
```

### PR DESCRIPTION
**Pull request by vic-blt**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
Fix type incompatibility for PredefinedOptions.ecma property with
MinifyOptions.ecma property from Terser

Closes #470

### Breaking Changes
NA

### Additional Info
NA

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export = TerserPlugin;
 /**
  * @typedef {Object} PredefinedOptions
  * @property {boolean} [module]
- * @property {any} [ecma]
+ * @property {5 | 2015 | 2016 | 2017 | 2018 | 2019 | 2020 | number | string} [ecma]
```
Comment (alexander-akait) [inline types/index.d.ts:58]: Webpack supports 2021/2022 too

Comment (vic-blt) [reply types/index.d.ts]: Updated with missing `2021 | 2022`

Comment (vic-blt) [reply types/index.d.ts]: Actually, I changed to use `TerserECMA` type
